Pt 98 nextconfigerror
0xbase-Corp/portfolio_ui pull request #18
Opened 2024-02-20 14:24 UTC by ItsFaizan

# [[PT-XXX]](https://0xbase.atlassian.net/browse/PT-XXXX) - PR title

### Description

> Remember to adjust the PR Title in this format [PT-XXX] - Title Name

2024-02-20 19:16 UTC, fuddin95 requested changes

2024-02-20 19:16 UTC, fuddin95 commented on src/components/drawer/Drawer.tsx
> +      </Box>
You can remove this and render {children } here

2024-02-20 19:16 UTC, fuddin95 commented on src/components/drawer/Drawer.tsx
> +export default function ResponsiveDrawer(props: Props) {
please export a react functional component using arrow syntax like before

2024-02-20 19:16 UTC, fuddin95 commented on src/components/drawer/Drawer.tsx
> +  const { window } = props
you can destructure window props in function like so

2024-02-20 19:16 UTC, fuddin95 commented on src/components/drawer/Drawer.tsx
> +  const drawer = (
you can name this `drawerItems`

2024-02-20 19:16 UTC, fuddin95 commented on src/app/dashboard/page.tsx
> +import PermanentDrawerLeft from '@/components/drawer/Drawer'
Your function name is ResponsiveDrawer not `PermanentDrawerLeft`

2024-02-20 19:16 UTC, fuddin95 commented on src/components/drawer/Drawer.tsx
> +  window?: () => Window
window is a global variable no need in props

2024-02-20 19:16 UTC, fuddin95 commented on src/components/drawer/Drawer.tsx
> +      <CssBaseline />
why do we need `<CssBaseline />` here?

2024-02-20 19:16 UTC, fuddin95 commented on src/components/drawer/Drawer.tsx
> +      </AppBar>
Lets seperate the app bar in a seperate file in the same folder maybe `DrawerAppBar.tsx`

2024-02-20 19:16 UTC, fuddin95 commented on src/components/drawer/Drawer.tsx
> +            FOLIO NOMICS
Title should be a prop

2024-02-20 19:16 UTC, fuddin95 commented on src/app/dashboard/page.tsx
> +      <PermanentDrawerLeft />
Render Lorem lapsum here as  children component

2024-02-21 16:52 UTC, ItsFaizan commented on src/components/drawer/Drawer.tsx
> +      </Box>
Resolved

2024-02-21 16:52 UTC, ItsFaizan commented on src/components/drawer/Drawer.tsx
> +export default function ResponsiveDrawer(props: Props) {
Done

2024-02-21 16:52 UTC, ItsFaizan commented on src/components/drawer/Drawer.tsx
> +  const drawer = (
Done

2024-02-21 16:55 UTC, ItsFaizan commented on src/app/dashboard/page.tsx
> +import PermanentDrawerLeft from '@/components/drawer/Drawer'
Done

2024-02-21 16:57 UTC, ItsFaizan commented on src/components/drawer/Drawer.tsx
> +      <CssBaseline />
Removed it came from Mui Webiste we already have it in layout.tsx

2024-02-21 16:59 UTC, ItsFaizan commented on src/components/drawer/Drawer.tsx
> +      </AppBar>
Done

2024-02-21 18:53 UTC, ItsFaizan commented on src/app/dashboard/page.tsx
> +      <PermanentDrawerLeft />
Done

2024-02-21 19:38 UTC, ItsFaizan commented on src/components/drawer/Drawer.tsx
> +  const { window } = props
Resolved

2024-02-21 19:38 UTC, ItsFaizan commented on src/components/drawer/Drawer.tsx
> +  window?: () => Window
Done

2024-02-21 20:01 UTC, merged