[PT-123]-ExpandableRows
0xbase-Corp/portfolio_ui pull request #25
Opened 2024-03-08 11:18 UTC by ItsFaizan

# [PT-123](https://0xbase.atlassian.net/browse/PT-123?atlOrigin=eyJpIjoiMjg5YzljZTJmMzc4NGI2Yzg3MGQ4NTNkNmYxMTMwM2IiLCJwIjoiaiJ9) - Expandable Rows

### Rows expanded with up and down buttons

2024-03-15 17:41 UTC, fuddin95 approved these changes

2024-03-15 17:41 UTC, fuddin95 commented on .env
> +NEXT_PUBLIC_DEBANK_ADDRESS=<your-debank-address>
Addresses are public therefore no need to create env variable for them you can hardcode them in code

2024-03-15 17:42 UTC, fuddin95 requested changes
you will need to resolve conflicts

2024-03-15 17:44 UTC, ItsFaizan commented on .env
> +NEXT_PUBLIC_DEBANK_ADDRESS=<your-debank-address>
ok

2024-03-20 04:14 UTC, fuddin95 approved these changes

2024-03-20 14:09 UTC, merged