PT-69-LoginModal
0xbase-Corp/portfolio_ui pull request #7
Opened 2024-01-31 17:14 UTC by ItsFaizan

# [PT-69](https://0xbase.atlassian.net/browse/PT-69?atlOrigin=eyJpIjoiOThlYTY1OGRmMjBmNDk3Mzk3MzMyNDMxNGZhYjE0ZTAiLCJwIjoiaiJ9) - LoginModal

Login Modal created and divider created as a custom component

2024-01-31 17:37 UTC, fuddin95 requested changes

2024-01-31 17:37 UTC, fuddin95 commented on src/container/LoginDialog.tsx
> +                Don't have an account? <Typography component="a" href='#' >Signup</Typography>
Now that we have `Signup Modal` we can show that view once a user clicks Signup

2024-01-31 17:37 UTC, fuddin95 commented on src/app/(home)/page.tsx
> +        throw new Error("Function not implemented.")
1. Your functions  are not beign used in the LoginDialog.
2. Lets avoid inline functions.
3. Lets not throw Errors rather think of handling errors gracefully

2024-01-31 17:47 UTC, fuddin95 commented on src/components/divider/CustomDivider.tsx
Generally the best practice is to keep the folder and component name same so you can just name the 
- folder `divider`
- component `Divider`

2024-02-01 13:53 UTC, ItsFaizan commented on src/app/(home)/page.tsx
> +        throw new Error("Function not implemented.")
Removed these functions

2024-02-01 18:33 UTC, merged